### ISSUE TITLE
Expose JavaScript in an NPM module

### ISSUE THREAD

**Issue by gavboulton** [alphagov/govuk_elements#299]
On passports we're using `govuk-elements-sass` for the GOVUK Elements sass modules. We'd also like to use the JS modules in the same way (particularly the `details/summary` polyfill).
## How would you expect it to work?

Can the JS modules be exposed via NPM in the same way as the sass? Could a specific NPM module for GOVUK Elements JS be created, ie `govuk-elements-js`? Or something that combines the sass and JS modules, ie `govuk-elements`?
## How does it work currently?

Only the sass is exposed via NPM in `govuk-elements-sass`.
## Tell us about your environment

We're using `govuk-elements-sass` in https://github.com/UKHomeOffice/passports-frontend-toolkit

**Comment by gemmaleigh** [comment]
Hi @gavboulton,

At present, the plan is to move the JS from govuk_elements to the govuk_frontend_toolkit - rather than create a new dependency. 

Most of the JS from govuk_elements exists in the govuk_frontend_toolkit already, [or will do soon](https://github.com/alphagov/govuk_frontend_toolkit/pull/315).

You're right, what's missing is the details/summary polyfill. This is because we are aware it has [issues](https://github.com/alphagov/govuk_elements/issues/277) and those haven't been fixed yet. 

I'll flag this as 'help wanted' and see if we can get the polyfill added to the govuk_frontend_toolkit, with tests.

**Comment by gavboulton** [comment]
Thanks @gemmaleigh. I'm aware of the issues, solving them will be a little tricky I think but I'll help out when/where I can.
