### ISSUE TITLE
Include guidelines for textareas

### ISSUE THREAD

**Issue by joefitter** [alphagov/govuk_elements#301]
There are no visual examples of textareas on [http://govuk-elements.herokuapp.com/form-elements/](http://govuk-elements.herokuapp.com/form-elements/). As a result different services have included their own custom textarea styles for width and height resulting in inconsistencies across applications.

A standard textarea with class `form-control` inherits the 50% width desktop, 100% width mobile as per text inputs, but they seem to only be high enough to show 2 lines

**Comment by gemmaleigh** [comment]
There are visual examples of textareas here: http://govuk-elements.herokuapp.com/form-elements/example-form-elements/

Our recommendation would be to ensure that the textarea is sized according to the response required - so rather than make these a default recommended height - they can vary in height to best fit the response.

I'll ensure this guidance is added to the main form elements page, thanks for suggesting it.

**Comment by joefitter** [comment]
Fab, thanks for getting back to me so quickly! I must have missed that page
