### ISSUE TITLE
Idea - a new 2/3 column which doesn't get smaller until screen-width

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_elements#381]
## How would you expect it to work?

Sometimes a service will use a 2/3 column with no column to the right, in order to keep line lengths readable.

In those situations, when a browser width is less than 1020px but more than 690px, it's not helpful for that 2/3 column to get smaller, but instead to stay 690px.

Register to vote works in this way.

**Comment by edwardhorsford** [comment]
I'd really like to see this. 👍

**Comment by nickcolley** [comment]
Instead of a grid system would this problem be solved with 'max-width'?

See http://tachyons.io/docs/typography/measure/

**Comment by selfthinker** [comment]
I would say using a 2/3 column without a 1/3 column next to it is using it wrong. But obviously using the full width column makes text less readable. Instead of changing the 2/3 column I would like to propose to add a modifier to the full width column which makes all content have a max-width (or add another div which does that).

**Comment by joelanman** [comment]
@selfthinker is there a difference in whats being proposed and your 'another div which [has max width]'? I think we should keep the concept of a full width column (I understand that gives us left and right margin/padding?) since there may be an element in it such as an image or table which should be full width.

**Comment by edwardhorsford** [comment]
Maybe something like `single-column` or `standard-column`? It's not full width, and it's not 2/3.

**Comment by selfthinker** [comment]
Yes, what I'm saying is that I don't agree with what's being proposed. If we changed the 2/3 width to stay 690px, what should happen to the 1/3 width column next to it if there is one? Right now it only drops below at the mobile breakpoint, not at the tablet breakpoint. The 2/3 column doesn't know or doesn't have a concept of being used correctly with another 1/3 column or not. You would want both cases to work differently.
That means we definitely need a new thing, whatever it is, or otherwise you would break existing 2/3 + 1/3 layouts in tablet-sized views.

As a side note, I find the concept of media queries based on viewports flawed in itself. Ideally I would want media queries based on content length, that also means dependent on font size and what else is next to it. What we really care about is the amount of characters in a line, not the viewport. It is only tied to the viewport because you know the content (which CSS doesn't) and if you cannot change the font size. E.g. if someone increases the font size, I would not want the 2/3 column restriction but full width.
But alas, CSS doesn't have such a concept. It could partly be solved by using `em` for layout widths and viewport checks instead of `px`, though.

**Comment by joelanman** [comment]
sorry I'm not proposing we change the current 2/3 column class, but to add a new class

**Comment by selfthinker** [comment]
Oh, sorry, I misunderstood that.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

I've copied the initial comment to the [layout issue in the backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/52).
