### ISSUE TITLE
Breadcrumb trail improvements

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#412]
I am wondering if the breadcrumb trail could be improved using a nav wrapper and also an ARIA label as suggested by W3C?

[https://www.w3.org/TR/WCAG20-TECHS/G65.html](https://www.w3.org/TR/WCAG20-TECHS/G65.html)

#### How would you expect it to work?
```
<nav class="breadcrumbs" aria-label="Breadcrumbs"> 
   <h2 class="visually-hidden">You are here:</h2> 
   <ul>
      <li><a href="/">GOV.UK elements</a></li> 
      <li>Typography</li>
   </ul> 
</nav>
```

#### How does it work currently?
```
 <div class="breadcrumbs">
  <ol>
    <li><a href="/">GOV.UK elements</a></li>
    <li>Typography</li>
  </ol>
</div>

**Comment by dsingleton** [comment]
I don't have answer to this, but there is some historic context in https://github.com/alphagov/static/pull/737 and https://github.com/alphagov/static/pull/238

**Comment by trevorsaint** [comment]
Thanks @dsingleton I will take a look at those.

**Comment by tombye** [comment]
I seem to remember some testing we did on this a while ago that showed all those we tested with could use and understand breadcrumbs in the current form. They weren't assistive tech users though so I'm not sure we've ever tested the semantics properly with users.

My only opinions on this are:
- we should test the pattern with the 'You are here' text visible to see if it needs to be hidden
- we should a content designer if the 'Breadcrumbs' label has the right text

I think the GOVUK Finding Things team were looking at breadcrumbs as part of looking at navigation. Wouldn't be surprised if @alextea would add some useful insight to this.

**Comment by alextea** [comment]
Yes indeed I do @tombye.

Our current breadcrumbs on GOV.UK are here: https://github.com/alphagov/static/blob/07c2bcfb04e87efc9f9bd0c75ecc33573bfd5fc2/app/views/govuk_component/breadcrumbs.raw.html.erb

We are using the `aria-current` attribute as explained by Leonie in this blog post: http://tink.uk/using-the-aria-current-attribute/

We're not using a `nav` tag, but I think that decision was made because we had a few other navigation elements on the page and it was confusing for screen reader users.

We are iterating the breadcrumbs as part of our navigation mission, so will look into this.

**Comment by gemmaleigh** [comment]
I'd like to resolve and close this issue @trevorsaint - if we add `aria-current` in the way Alex describes above - and we'll await further work on breadcrumbs from the GOV.UK Finding Things team?
