### ISSUE TITLE
Fieldset inside form group collapses margin on legend

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk_elements#515]
Margin's on `legend`'s collapse when inside `fieldset`
GOV.UK Elements (app) contains `legend { overflow: hidden;}` however this doesn't appear to be in GOV.UK Elements itself. 

Therefore examples in the App render differently than in the the kit / when you include elements.

**Comment by 36degrees** [comment]
After a bit of sleuthing we've worked out that this is due to a difference between the documentation on govuk-elements.herokuapp.com and what's currently in the prototype kit – the prototype kit isn't up to date with [this change](https://github.com/alphagov/govuk_elements/pull/484/files#diff-a026f0d58b91239f175301f35ab9c577R24).
