### ISSUE TITLE
Make form error examples more realistic

### ISSUE THREAD

**Issue by selfthinker** [alphagov/govuk_elements#555]
Most examples in the styleguide contain copy from real world examples. But there are some instances which have either "lorem ipsum" style text or text describing itself.
While that is not a big issue by itself, content is part of a service and also important for the user experience and accessibility.

Ideally we should add guidance and update the examples to reflect what the best content would be. Otherwise user experience will be inconsistent across services and it will be more difficult and time-consuming to write good copy.

#### How would you expect it to work?

All pages in the styleguide should contain real world examples.
Example error messages should cover all standard use cases.

#### How does it work currently?

[Error summary box and error messages](https://govuk-elements.herokuapp.com/errors/) say things like "Message to alert the user to a problem goes here" and "Descriptive link to the question with an error"

#### Suggesting a fix...

This is probably a bigger project and not quickly done. But when we briefly [talked about it before](https://github.com/alphagov/govuk_elements/pull/509#issuecomment-312286875), @stevenaproctor and @adamsilver said they were already working on something like that in a project.
It would be great if they could feed back their findings and if we (or they) could update the styleguide accordingly.

**Comment by gemmaleigh** [comment]
I'd like to see these updated. When the error message example pages were built - there wasn't agreement on the language to be used - which is why they use the generic "Error message goes here".

It was more important (at the time) to be able to show the examples, than to delay them while there was discussion around the error message text. They've been published with this generic text for quite a long time now, it would be good to update them.

Thanks @selfthinker, I'll assign this one to you.

**Comment by stevenaproctor** [comment]
@selfthinker We have not finished our work yet at HMRC but should be in a few weeks. I will post something here then. The examples definitely need to include recommended content.

For example, I have never seen an "Optional description of the errors and how to correct them" add value to the page. The heading and the message should do this.

Also, because "Descriptive link to the question with an error" and "Error message about personal details goes here" are different, people are writing messages like "Something is wrong with x" and "X must be..." When these are different, the generic message is not helpful enough and possibly having two slightly different errors may confuse people.

**Comment by selfthinker** [comment]
As my description contains three different issues, it makes sense to separate them.

> The structure of the [error example pages](https://govuk-elements.herokuapp.com/errors/example-form-validation-single-question-radio) don't reflect a real life example as we would usually not duplicate what's in the heading and the question. Also, the title is not standard, I guess because the example is only the main content and not the whole page.

Someone is already working on that in #552.

> The [typography page](https://govuk-elements.herokuapp.com/typography/) contains fake Latin. (Although that's much less important compared to the error messages. But then again, it's also easier to fix.)

I have just fixed that in #568.

I will remove those two things from the description so that this issue is only about the error messages.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.
